[package]
name = "clixy"
description = "A CLI tool."
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.16", features = ["cargo", "derive"] }
fs_extra = "1.3.0"
indicatif = "0.17.8"
rand = "0.8.5"
rayon = "1.10.0"
sha2 = "0.10.8"

[[bin]]
name = "clixy"
path = "src/main.rs"
