[package]
name = "clixy"
version = "0.12.0"
edition = "2024"
rust-version = "1.86.0"
description = "A CLI tool."
readme = "README.md"
repository = "https://github.com/Nanagalaxy/Clixy"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.37", features = ["cargo", "derive"] }
clap_complete = "4.5.48"
clap_complete_nushell = "4.5.5"
deunicode = "1.6.2"
digest = "0.10.7"
fs4 = "0.13.1"
hex = "0.4.3"
indicatif = "0.17.11"
md-5 = "0.10.6"
rand = "0.9.1"
rayon = "1.10.0"
sha1 = "0.10.6"
sha2 = "0.10.9"
sha3 = "0.10.8"

[dev-dependencies]
rstest = "0.25.0"
tempfile = "3.19.1"

[[bin]]
name = "clixy"
path = "src/main.rs"

[features]
default = ["describe"]
describe = []
crypto = []
file = []
random = []
